sudo: required
language: python
python:
- 3.6
- 3.7
- 3.8
install:
- pip install -r dev_requirements.txt
script:
- python setup.py develop
- python setup.py test
- python setup.py sdist
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: pypi
  user: wesyoung
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.8"
  password:
    secure: ISgNogYXl79zNTrLXCHXz/QkAIoLl9NBB/9cGQiKT5KxIr751djZocF/bpjQJy57bU6zqFOE+i2UGiiRYCs9acdf+THl9BR+OHxetKG3jeVeeki0gJP6k5DbvLo4hkCmsf8+R5bo9TwnZ8LY1SIs52qNvk+l4hwqUC70TBTEYMOyZwT7OWE3f4Jt1U7sPLSgg06wTS/0eKqLwBmfwUwbJwsTu19ugbfyd0MvBq6DrrOVxjvDXrm9G+f3BazlDH/bRD7K4JvOvaGEhVwTyj2N/nE3czhVLNsnRcrD+4240CsVyY89/VDm+kMXd7/LQEf5t9KlCVinYzB/yVGW3MT6k6XYinT9dMNHyH5qycwFmLJ7J8/Muh7qf3wUvLFqqizzjjcKucWjh4EjLvtKOyDc3mwwmqsMR80iAjKVkjMnEXioAGweL4np1pdrc3wQyQSOzEWQdLb45+2Pp39QXaH9nHGbVE/dxNNW3FLEnO/SLeTX54BTKbuo0QKniwuWIG0zWsHqCecQz2je+MK66jlfDS9ME4JWiXuEbeoAutvtah2QGskJRd827rVw0Fe7trKAgswzQM4ewChi5MAXWZhtok+z9PdyngYO1kUyoNnWVPZLgQI3Hdcs/lSsJtpokKPGAdeUr9h59INAJ44Zrb11xFd86jyPa4l6ERVNatdyOmQ=
