sudo: required
language: python
python:
- 3.6
- 3.7
- 3.8
install:
- pip install -r dev_requirements.txt
script:
- python setup.py develop
- python setup.py test
- python setup.py sdist
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: pypi
  user: __token__
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.8"
  password:
    secure: elRo6pKWuXaTHWEUWn2qGiKudr6I81JtvYbnJ7XsaoGnubTM8DX1Ke2uxI+AZeZwDy9Nq8zn/dlOsbI7N2CNaJ0Q1y8GwjV49mXdRyuo6DQyZwHImYWBxwoCGOnPA6qPyF6d04IGIlA/7VlG1kNNiC23MkJuqY2FF3mESu87X6swiCWkP1bmNmZKt0b8UKG8XqhACTAwua4IFv03TBu6FNm2ugav1ZqiX56Gwu3d1izXW6mn+3Qt31S/mFak9DBGtU30RoL5y3EMV0oDtP7m4h4FjCKzXwaolBqCfJeyKdukqmHU0fyZzE2CK0Zusett0wO3/uT2TL/+6oC2efBZrX6XeabBhNtE+Wn7rSSxkpsJ8N/0QEMQdn66Ywoy9B/eba01Gy3TLDRj8l442jjpDswoIUprxDq98h8DVKh29iLmG8eRRKk6UQ/ZiJK4EVxZVgZ67WsEHCSuLsI6QhZNGQb1IpNKjqUogFM1zUN5BZcewdaXl+cUzdF7OzdpMci1srXheBE+nsLcMUJ/O+o4w5Ga8nCdzcQnoS7kCg189YQtxEH06pTrhoi22M0zSbQSWE+DyFK+vTXGMCoLgt366IOeUOM8SSolaZa2DiqM1K1gTIZkLDFktHXI1Hwr6ZwjEE+/0dJKTDFaQZjIuhxPLgKtoqddKCd8uos/eGaR9jg=
